import uuid
from builtins import property as python_property
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Numeric, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from app.models.mixins import TimestampMixin, UUIDPkMixin


class CallSession(UUIDPkMixin, TimestampMixin, Base):
    __tablename__ = "call_sessions"

    exotel_call_id: Mapped[str | None] = mapped_column(String(64), unique=True, index=True)
    # Always set when the host is known at call time (every voice-pipeline
    # path resolves one), independent of property_id -- Lead Agent calls
    # legitimately have no single property, but still belong to a host.
    # Dashboard queries (calls/guests/analytics) must scope by this, not by
    # property ownership, or Lead Agent calls become invisible (property_id
    # is never IN any property-id list when it's NULL).
    user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL"), index=True
    )
    property_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("properties.id", ondelete="SET NULL")
    )
    guest_profile_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("guest_profiles.id", ondelete="SET NULL")
    )
    # The Lead this call is currently associated with -- may be a lead
    # created BY this call (the common case) or one reused from an earlier
    # call by the same returning guest, still open/contacted (see
    # lead_service.py's reuse logic). Deliberately a separate FK from
    # Lead.call_session_id (which stays 1:1, meaning "the call that
    # originally created this lead") -- many call_sessions can share one
    # lead_id, so a guest's whole in-progress inquiry stays on one Lead row
    # across follow-up calls instead of fragmenting into one per call.
    # use_alter=True: leads.call_session_id -> call_sessions.id and this
    # column form a circular FK dependency between the two tables --
    # without it, SQLAlchemy can't order CREATE/DROP TABLE (or the test
    # suite's per-test cleanup, which deletes in dependency order) and
    # raises CircularDependencyError. use_alter defers this one constraint
    # to a separate ALTER TABLE after both tables already exist.
    lead_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("leads.id", ondelete="SET NULL", use_alter=True, name="fk_call_sessions_lead_id_leads"),
        index=True,
    )
    caller_number: Mapped[str | None] = mapped_column(String(32))
    recording_url: Mapped[str | None] = mapped_column(String(1024))
    transcript: Mapped[str | None] = mapped_column(Text)
    # Structured, host-facing summary (schemas/call_summary.py's CallSummary
    # shape) generated by call_summary_service.summarize_call via
    # on_pipeline_finished, once the call ends -- NULL until then (or if
    # generation fails, degrades to CallSummary's own fallback shape rather
    # than leaving this NULL forever).
    ai_summary: Mapped[dict | None] = mapped_column(JSONB)
    status: Mapped[str] = mapped_column(String(32), default="in_progress", server_default="in_progress")
    urgency: Mapped[str | None] = mapped_column(String(16))
    # Populated by call_classification_service via on_pipeline_finished, once
    # the call ends -- see app/services/call_classification_service.py for
    # the full taxonomy. "UNKNOWN" until classified (or if classification
    # fails), never null, so every historical/in-flight row degrades
    # gracefully with no backfill needed.
    call_type: Mapped[str] = mapped_column(String(32), default="UNKNOWN", server_default="UNKNOWN", index=True)
    classification_confidence: Mapped[float | None] = mapped_column(Numeric(4, 3))
    classification_reason: Mapped[str | None] = mapped_column(Text)
    revenue_attributed: Mapped[float] = mapped_column(Numeric(10, 2), default=0, server_default="0")
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    ended_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # Set when a host clears a Service Request row from the live Requests
    # tab (frontend/src/app/dashboard/leads/page.tsx) -- a soft dismiss, not
    # a delete: the row moves out of the live list into a read-only
    # "completed" view the host can still refer back to. NULL means still
    # live/outstanding.
    dismissed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    property: Mapped["Property"] = relationship(back_populates="call_sessions")
    guest_profile: Mapped["GuestProfile"] = relationship(back_populates="call_sessions")
    notifications: Mapped[list["Notification"]] = relationship(back_populates="call_session")
    # Navigates via lead_id above, not Lead.call_session_id -- explicit
    # foreign_keys needed since there are now two independent FK paths
    # between these two tables (this one, and Lead.call_session_id, which
    # has no relationship object of its own since nothing reads it).
    lead: Mapped["Lead"] = relationship(foreign_keys=[lead_id])

    # Plain @property breaks here -- the `property` relationship column
    # above shadows the builtin `property` decorator for the rest of this
    # class body, since a Python class body is just sequential execution
    # in a shared namespace. Use the aliased import instead.
    @python_property
    def duration_minutes(self) -> float | None:
        if self.started_at is None or self.ended_at is None:
            return None
        return round((self.ended_at - self.started_at).total_seconds() / 60, 1)

    @python_property
    def guest_name(self) -> str | None:
        # The Lead row (filled in via the update_lead tool during the call)
        # is the more reliable source -- a guest profile only has a name if
        # they're a repeat caller whose profile was edited separately.
        if self.lead is not None and self.lead.guest_name:
            return self.lead.guest_name
        if self.guest_profile is not None:
            return self.guest_profile.name
        return None

    @python_property
    def guest_phone(self) -> str | None:
        # caller_number is the raw signaling-level identity (e.g.
        # "browser-test" for in-dashboard tests, or absent if the agent
        # never confirmed it out loud) -- the Lead's phone field is what the
        # guest actually said during the call, which is what a host wants
        # to see and call back.
        if self.lead is not None and self.lead.phone:
            return self.lead.phone
        return self.caller_number
