"""drop vapi columns

Revision ID: 08b6a6949f77
Revises: 8d937521de4c
Create Date: 2026-06-26 23:03:35.144444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b6a6949f77'
down_revision: Union[str, None] = '8d937521de4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_sessions_vapi_call_id'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_exotel_call_id'), table_name='call_sessions')
    op.create_index(op.f('ix_call_sessions_exotel_call_id'), 'call_sessions', ['exotel_call_id'], unique=True)
    op.drop_column('call_sessions', 'vapi_call_id')
    op.drop_index(op.f('ix_properties_vapi_phone_number_id'), table_name='properties')
    op.drop_column('properties', 'vapi_phone_number_id')
    op.drop_column('properties', 'vapi_assistant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('vapi_assistant_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('vapi_phone_number_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_properties_vapi_phone_number_id'), 'properties', ['vapi_phone_number_id'], unique=False)
    op.add_column('call_sessions', sa.Column('vapi_call_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_call_sessions_exotel_call_id'), table_name='call_sessions')
    op.create_index(op.f('ix_call_sessions_exotel_call_id'), 'call_sessions', ['exotel_call_id'], unique=False)
    op.create_index(op.f('ix_call_sessions_vapi_call_id'), 'call_sessions', ['vapi_call_id'], unique=True)
    # ### end Alembic commands ###
