"""add airbnb_listing_id to properties

Revision ID: 750ff224edb7
Revises: df8097774c5d
Create Date: 2026-06-28 12:07:19.997338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '750ff224edb7'
down_revision: Union[str, None] = 'df8097774c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('airbnb_listing_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_properties_airbnb_listing_id'), 'properties', ['airbnb_listing_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_airbnb_listing_id'), table_name='properties')
    op.drop_column('properties', 'airbnb_listing_id')
    # ### end Alembic commands ###
