"""add usp to properties, agent customization fields to users

Revision ID: 896a916936e2
Revises: a1e3085944c1
Create Date: 2026-06-28 21:10:29.217196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896a916936e2'
down_revision: Union[str, None] = 'a1e3085944c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('usp', sa.String(length=280), nullable=True))
    op.add_column('users', sa.Column('agent_first_message', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('agent_persona', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('agent_escalation_phrase', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'agent_escalation_phrase')
    op.drop_column('users', 'agent_persona')
    op.drop_column('users', 'agent_first_message')
    op.drop_column('properties', 'usp')
    # ### end Alembic commands ###
