"""initial schema

Revision ID: 8d937521de4c
Revises: 
Create Date: 2026-06-25 20:13:18.385959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d937521de4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_profiles',
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('total_stays', sa.Integer(), server_default='0', nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_profiles_phone'), 'guest_profiles', ['phone'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('tier', sa.String(length=32), server_default='tier_1', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('properties',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('exophone', sa.String(length=32), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ical_url', sa.String(length=1024), nullable=True),
    sa.Column('house_rules', sa.Text(), nullable=True),
    sa.Column('faq', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('check_in_time', sa.String(length=8), server_default='14:00', nullable=False),
    sa.Column('check_out_time', sa.String(length=8), server_default='11:00', nullable=False),
    sa.Column('max_guests', sa.Integer(), server_default='4', nullable=False),
    sa.Column('vapi_assistant_id', sa.String(length=64), nullable=True),
    sa.Column('vapi_phone_number_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_exophone'), 'properties', ['exophone'], unique=True)
    op.create_index(op.f('ix_properties_vapi_phone_number_id'), 'properties', ['vapi_phone_number_id'], unique=False)
    op.create_table('bookings',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('guest_phone', sa.String(length=32), nullable=True),
    sa.Column('guest_name', sa.String(length=255), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('platform', sa.String(length=32), server_default='airbnb', nullable=False),
    sa.Column('source_uid', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='confirmed', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'source_uid', name='uq_booking_property_source_uid')
    )
    op.create_table('call_sessions',
    sa.Column('exotel_call_id', sa.String(length=64), nullable=True),
    sa.Column('vapi_call_id', sa.String(length=64), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('guest_profile_id', sa.UUID(), nullable=True),
    sa.Column('caller_number', sa.String(length=32), nullable=True),
    sa.Column('recording_url', sa.String(length=1024), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='in_progress', nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=True),
    sa.Column('revenue_attributed', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_profile_id'], ['guest_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_sessions_exotel_call_id'), 'call_sessions', ['exotel_call_id'], unique=False)
    op.create_index(op.f('ix_call_sessions_vapi_call_id'), 'call_sessions', ['vapi_call_id'], unique=True)
    op.create_table('pricing_rules',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technicians',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), server_default='5.0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('call_session_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('urgency', sa.String(length=16), server_default='low', nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='new', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('technicians')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_call_sessions_vapi_call_id'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_exotel_call_id'), table_name='call_sessions')
    op.drop_table('call_sessions')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_properties_vapi_phone_number_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_exophone'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_guest_profiles_phone'), table_name='guest_profiles')
    op.drop_table('guest_profiles')
    # ### end Alembic commands ###
