"""scope airbnb_listing_id uniqueness to per-user

Revision ID: 96046254326b
Revises: 750ff224edb7
Create Date: 2026-06-28 13:01:13.708992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96046254326b'
down_revision: Union[str, None] = '750ff224edb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_airbnb_listing_id'), table_name='properties')
    op.create_index(op.f('ix_properties_airbnb_listing_id'), 'properties', ['airbnb_listing_id'], unique=False)
    op.create_unique_constraint('uq_properties_user_airbnb_listing', 'properties', ['user_id', 'airbnb_listing_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_properties_user_airbnb_listing', 'properties', type_='unique')
    op.drop_index(op.f('ix_properties_airbnb_listing_id'), table_name='properties')
    op.create_index(op.f('ix_properties_airbnb_listing_id'), 'properties', ['airbnb_listing_id'], unique=True)
    # ### end Alembic commands ###
