"""add user_id to call_sessions for lead-agent call attribution

Revision ID: a1e3085944c1
Revises: 96046254326b
Create Date: 2026-06-28 14:54:22.509509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e3085944c1'
down_revision: Union[str, None] = '96046254326b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_sessions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_call_sessions_user_id'), 'call_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'call_sessions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Backfill existing rows from their property's owner, where one is set.
    # Rows with no property_id (and pre-existing Lead Agent test calls) have
    # no way to recover the host and stay NULL -- they were already
    # invisible on every dashboard page before this migration.
    op.execute(
        """
        UPDATE call_sessions
        SET user_id = properties.user_id
        FROM properties
        WHERE call_sessions.property_id = properties.id
          AND call_sessions.user_id IS NULL
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'call_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_call_sessions_user_id'), table_name='call_sessions')
    op.drop_column('call_sessions', 'user_id')
    # ### end Alembic commands ###
