"""add neighborhood_info to properties

Revision ID: c4147f84e6a1
Revises: 896a916936e2
Create Date: 2026-06-28 21:18:22.243053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4147f84e6a1'
down_revision: Union[str, None] = '896a916936e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('neighborhood_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'neighborhood_info')
    # ### end Alembic commands ###
