"""add leads and faq entries

Revision ID: df8097774c5d
Revises: 08b6a6949f77
Create Date: 2026-06-27 22:24:53.268725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df8097774c5d'
down_revision: Union[str, None] = '08b6a6949f77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('call_session_id', sa.UUID(), nullable=True),
    sa.Column('guest_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=True),
    sa.Column('check_out', sa.Date(), nullable=True),
    sa.Column('num_guests', sa.Integer(), nullable=True),
    sa.Column('purpose_of_stay', sa.String(length=255), nullable=True),
    sa.Column('budget', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preferred_location', sa.String(length=255), nullable=True),
    sa.Column('properties_discussed', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('questions_asked', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('support_requests', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('lead_temperature', sa.String(length=16), nullable=True),
    sa.Column('lead_source', sa.String(length=64), server_default='voice_call', nullable=False),
    sa.Column('conversation_summary', sa.Text(), nullable=True),
    sa.Column('next_follow_up', sa.String(length=255), nullable=True),
    sa.Column('escalated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('transferred_to_host', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_session_id')
    )
    op.add_column('users', sa.Column('lead_exophone', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_users_lead_exophone'), 'users', ['lead_exophone'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_lead_exophone'), table_name='users')
    op.drop_column('users', 'lead_exophone')
    op.drop_table('leads')
    op.drop_table('faq_entries')
    # ### end Alembic commands ###
