"""add lead status/occasion and unanswered_questions

Revision ID: f3cebf679a80
Revises: c4147f84e6a1
Create Date: 2026-07-07 12:21:26.620651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3cebf679a80'
down_revision: Union[str, None] = 'c4147f84e6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unanswered_questions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('call_session_id', sa.UUID(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('normalized_question', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('resolved_faq_entry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_faq_entry_id'], ['faq_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_unanswered_questions_user_normalized_status', 'unanswered_questions', ['user_id', 'normalized_question', 'status'], unique=False)
    op.create_index('ix_unanswered_questions_user_property', 'unanswered_questions', ['user_id', 'property_id'], unique=False)
    op.add_column('leads', sa.Column('status', sa.String(length=16), server_default='open', nullable=False))
    op.add_column('leads', sa.Column('occasion', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'occasion')
    op.drop_column('leads', 'status')
    op.drop_index('ix_unanswered_questions_user_property', table_name='unanswered_questions')
    op.drop_index('ix_unanswered_questions_user_normalized_status', table_name='unanswered_questions')
    op.drop_table('unanswered_questions')
    # ### end Alembic commands ###
