"""StyleComplianceMonitor -- a streaming observer that checks whether the
LLM's response matches the expected ConversationStyle, WITHOUT ever
buffering the response or calling another LLM.

Replaces response_compliance.py's ResponseComplianceProcessor entirely (see
git history for that file's removal in this same change). That processor
buffered the ENTIRE response unconditionally on every turn and, on a FAIL,
made a second, direct, non-streaming LLM completion call to regenerate the
reply -- up to 8 seconds of dead air on a live phone call, the single
largest architectural problem this redesign exists to fix. This module
removes both: it never buffers more than a small rolling tail for scoring
purposes, and it never calls an LLM anywhere in this file.

Architecture boundary: this validator's check() takes a ConversationStyle
snapshot, not the whole ConversationState -- narrowing the input type is
itself the guarantee that a style/language validator can never reach into
unrelated conversation facts (booking slots, escalation flags, property
selections). A future PricingValidator/PropertyReferenceValidator would
each define their own similarly narrow input type, never the full
ConversationState either.

Streaming design: observe(chunk) is called on every LLMTextFrame the moment
it arrives and only appends to a small bounded rolling tail (no await, no
blocking, the frame is always forwarded immediately regardless of what is
observed) -- language correctness is never enforced by withholding audio.
finalize(turn_index) runs once, at LLMFullResponseEndFrame, against the
complete shadow-accumulated text (more reliable than the rolling tail alone,
since a short opening sentence can be ambiguous on its own) and returns the
ValidationResult that gets appended to ConversationQuality. On a confirmed
FAIL, the only effect is ConversationQuality.record() setting
pending_style_correction=True -- read by exactly one consumer
(state_prompt_sync.py), which asks ConversationStyle's own render_style_block
for a more emphatic version of the SAME style block on the NEXT turn. No
frame is ever rewritten, cut, or regenerated by this module.
"""

from __future__ import annotations

import dataclasses
import time
from typing import TYPE_CHECKING

from pipecat.frames.frames import Frame, LLMFullResponseEndFrame, LLMFullResponseStartFrame, LLMTextFrame
from pipecat.processors.frame_processor import FrameDirection, FrameProcessor

from app.voice.conversation_quality import ConversationQuality, ValidationResult
from app.voice.language_heuristics import MIN_CHARS_FOR_CONFIDENT_VERDICT, devanagari_ratio, has_hinglish_token

if TYPE_CHECKING:
    from app.voice.conversation_style import ConversationStyle

# Same two language families the rest of this codebase's language mechanism
# already recognizes (state_prompt_sync.py's own _LANGUAGE_DISPLAY_NAMES,
# language_sync.py's own _HINDI_LANGUAGES) -- ConversationStyle.language is
# already a 3-way Literal ("ENGLISH"/"HINDI"/"HINGLISH"), so this module
# reads that field directly rather than re-deriving a language family from
# a pipecat Language enum the way the old response_compliance.py had to.


def _expected_language_family(style: "ConversationStyle | None") -> str | None:
    """Returns "hindi", "english", or None (nothing known yet, e.g. before
    the Style Engine has computed anything -- the very first turn of a
    call). "HINGLISH" maps to the same "hindi" family used below, since
    GOLDEN_RULES' own Urban Hinglish rule and this module's compliance bar
    are the same for both (Roman-script Hindi/Hinglish is equally
    compliant, per LanguageComplianceRule's original reasoning, preserved
    here unchanged)."""
    if style is None:
        return None
    if style.language == "ENGLISH":
        return "english"
    return "hindi"


class StyleComplianceRule:
    """The style/language validator. Deterministic script/token heuristic
    only -- no NLP, no embeddings, no LLM call. check() is a pure function
    of (text, ConversationStyle); observe()/finalize() below are the
    streaming wrapper around it."""

    name = "style_compliance"

    def check(self, text: str, style: "ConversationStyle | None") -> ValidationResult:
        start = time.perf_counter()
        expected = _expected_language_family(style)

        if expected is None:
            return ValidationResult(
                rule=self.name,
                severity="INFO",
                confidence=1.0,
                metadata={"reason": "no expected style known yet"},
                processing_time_ms=round((time.perf_counter() - start) * 1000, 3),
            )

        ratio, letter_count = devanagari_ratio(text)

        if letter_count < MIN_CHARS_FOR_CONFIDENT_VERDICT:
            return ValidationResult(
                rule=self.name,
                severity="WARNING",
                confidence=0.3,
                metadata={
                    "expected_language": expected,
                    "observed_language": "indeterminate",
                    "letter_count": letter_count,
                },
                processing_time_ms=round((time.perf_counter() - start) * 1000, 3),
            )

        has_hindi_signal = ratio > 0.05 or has_hinglish_token(text)
        observed = "hindi" if has_hindi_signal else "english"
        metadata = {
            "expected_language": expected,
            "observed_language": observed,
            "devanagari_ratio": round(ratio, 3),
        }
        elapsed_ms = round((time.perf_counter() - start) * 1000, 3)

        if expected == "english":
            if ratio > 0.3:
                return ValidationResult(
                    rule=self.name,
                    severity="FAIL",
                    confidence=min(1.0, 0.5 + ratio),
                    metadata={**metadata, "reason": "expected English but response is substantially Devanagari"},
                    processing_time_ms=elapsed_ms,
                )
            return ValidationResult(
                rule=self.name, severity="INFO", confidence=1.0, metadata=metadata, processing_time_ms=elapsed_ms
            )

        # expected == "hindi" (covers both HINDI and HINGLISH styles).
        # GOLDEN_RULES' Urban Hinglish rule requires Roman-script rendering,
        # so pure-Latin output is CORRECT, not a violation -- only a
        # response with no Devanagari AND no recognized Hinglish token at
        # all is a genuine plain-English reply to a Hindi/Hinglish-expected
        # turn (the exact regression shape this whole mechanism exists to
        # catch, confirmed on the real production call trace this session).
        if has_hindi_signal:
            return ValidationResult(
                rule=self.name, severity="INFO", confidence=1.0, metadata=metadata, processing_time_ms=elapsed_ms
            )
        return ValidationResult(
            rule=self.name,
            severity="FAIL",
            confidence=0.85,
            metadata={
                **metadata,
                "reason": "expected Hindi/Hinglish but response has no Devanagari and no recognized "
                "Hinglish token -- plain English reply to a Hindi/Hinglish-expected turn",
            },
            processing_time_ms=elapsed_ms,
        )


# How much recent text the streaming observer keeps for its own reference --
# not currently read by anything (finalize() re-checks the full
# shadow-accumulated text, which is more reliable than a tail alone for a
# short opening sentence), kept small and bounded so this can never grow
# unbounded across a long response. Exists as the concrete implementation of
# "validators observe streams, never buffer the whole response" for this
# specific validator.
_ROLLING_TAIL_CHARS = 200


class StyleComplianceMonitor(FrameProcessor):
    """Streaming observer wiring StyleComplianceRule into the live pipeline.
    Sits after meta_commentary_guard (before the tool-fidelity guards) --
    see pipeline.py's own comment for why: it should score the model's own
    original wording, not a guard-substituted safe line. Never buffers,
    never blocks, never rewrites -- every frame is forwarded the instant it
    arrives, unconditionally."""

    def __init__(
        self,
        conversation_state=None,
        quality: ConversationQuality | None = None,
        rule: StyleComplianceRule | None = None,
    ):
        super().__init__()
        # conversation_state is read ONLY for its .conversation_style
        # reference (a ConversationStyle snapshot) -- never for any other
        # field, preserving the narrow-input-type guarantee described in
        # this module's own docstring. Optional so a call site that hasn't
        # wired ConversationState yet degrades to a no-op check, same
        # pattern every other optional-state processor in this codebase
        # already uses.
        self._conversation_state = conversation_state
        self._quality = quality
        self._rule = rule if rule is not None else StyleComplianceRule()
        self._shadow_text = ""
        self._rolling_tail = ""
        self._turn_index = 0

    async def process_frame(self, frame: Frame, direction: FrameDirection):
        await super().process_frame(frame, direction)

        if isinstance(frame, LLMFullResponseStartFrame):
            self._shadow_text = ""
            self._rolling_tail = ""
            self._turn_index += 1
            await self.push_frame(frame, direction)
            return

        if isinstance(frame, LLMTextFrame):
            self._observe(frame.text)
            await self.push_frame(frame, direction)
            return

        if isinstance(frame, LLMFullResponseEndFrame):
            if self._shadow_text.strip():
                self._finalize()
            await self.push_frame(frame, direction)
            return

        await self.push_frame(frame, direction)

    def _observe(self, chunk: str) -> None:
        """Never blocks, never withholds -- purely bookkeeping for the
        eventual finalize() call. This method's entire cost is a string
        concatenation and a slice, no regex, no scoring (scoring only
        happens once, in finalize(), against the complete text)."""
        self._shadow_text += chunk
        self._rolling_tail = (self._rolling_tail + chunk)[-_ROLLING_TAIL_CHARS:]

    def _finalize(self) -> None:
        style = self._conversation_state.conversation_style if self._conversation_state is not None else None
        result = dataclasses.replace(self._rule.check(self._shadow_text, style), turn_index=self._turn_index)
        if self._quality is not None:
            self._quality.record(result)
